name: Deploy to Basecode via FTP

on:
  push:
    branches:
      - basecode  # Â¡Solo se ejecuta cuando subes cambios a la rama de Basecode!

jobs:
  web-deploy:
    name: ðŸš€ Deploying to Basecode
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3

    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.BASECODE_FTP_SERVER }}
        username: ${{ secrets.BASECODE_FTP_USERNAME }}
        password: ${{ secrets.BASECODE_FTP_PASSWORD }}
        server-dir: /public_html/mi_primera_comunion/  # Ruta que has enseÃ±ado en la captura
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/01_HISTORIAL_Y_BACKUPS/**
          **/*.zip
          README.md
          package-lock.json
          package.json
          vite.config.js
          .gitignore
